Remove explicit update-alternatives calls from install-theos

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -10,8 +10,7 @@
 # 7 - Toolchain install failed
 # 8 - SDK install failed
 # 9 - Checkra1n '/opt' setup failed
-# 10 - fakeroot adjustment failed
-# 11 - Enabling Linux binary compat on FreeBSD failed
+# 10 - Enabling Linux binary compat on FreeBSD failed
 
 set -e
 
@@ -295,7 +294,7 @@ darwin_mobile() {
 				exit 3
 			fi
 		fi
-		
+
 		# Check desire for Swift support
 		update "Checking desire for Swift support..."
 		read -p "Would you like to be able to work with Swift? If so, an additional package will need to be installed. [y/n]" confirm
@@ -377,28 +376,6 @@ linux() {
 			common "Additional dependencies may also be required depending on what your distro provides."
 			;;
 	esac
-
-	# favor fakeroot backend with greatest support (circumvents harsher tcp restrictions on some distros (e.g., Fedora 41))
-	update "Adjusting fakeroot to favor sysv > tcp..."
-	sudo update-alternatives --set fakeroot /usr/bin/fakeroot-sysv \
-		&& update "fakeroot adjusted!" \
-		|| (error "fakeroot adjustment seems to have encountered an error. Please see the log above."; exit 10)
-
-	# Check for WSL
-	update "Checking for WSL..."
-	rel="$(uname -r)"
-	if [[ ${rel,,} =~ microsoft ]]; then
-		if ! [[ $rel =~ WSL2 ]]; then
-			update "WSL1! Need to adjust fakeroot as no sysv..."
-			sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp \
-				&& update "fakeroot adjusted!" \
-				|| (error "fakeroot adjustment seems to have encountered an error. Please see the log above."; exit 10)
-		else
-			update "WSL2! Nothing to do here."
-		fi
-	else
-		update "Seems you're not using WSL. Moving on..."
-	fi
 
 	set_theos
 	get_theos
@@ -499,7 +476,7 @@ linux() {
 # 	sudo service linux start
 # 	sudo pkg install -y linux_base-c7 \
 # 		&& update "Linux binary compatibility successfully enabled!" \
-# 		|| (error "Linux binary compatibility command seems to have encountered an error. Please see the log above."; exit 11)
+# 		|| (error "Linux binary compatibility command seems to have encountered an error. Please see the log above."; exit 10)
 
 # 	# Compatibility with common Theos commands
 # 	# TODO: Should we be doing this?
