Add macOS support to 'install-theos'

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -33,16 +33,94 @@ CSHELL=$(ps -p $$ | tail -1 | grep -o '[^ ]*$' | sed 's/[^[:alpha:]]//g')
 # The work
 darwin() {
     common "Platform: Darwin"
+
+    # Check for Xcode
+    XCODE=$(xcode-select -p)
+    if ! [[ "${XCODE}" == "/Applications/Xcode.app/Contents/Developer" ]]; then
+        error "Xcode is mandatory. The Command Line Tools package isn't sufficient for Theos to work. Xcode provides toolchains for all Apple platforms."
+        exit 3
+    fi
+
+    # Check for Homebrew
+    update "Preparing to install dependencies..."
+    if ! command -v brew &> /dev/null; then
+        read -p "Homebrew, which provides tools Theos depends on, is not installed. Would you like to have it installed for you? [y/n]" hbrew
+        if [[ "${hbrew,,}" == "y" || "${hbrew,,}" == "yes" ]]; then
+            bash "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && update "Homebrew has been successfully installed!" || (error "Homebrew install command seems to have encountered an error. Please see the log above." && exit 5)
+        else
+            error "Homebrew provides tools Theos depends on and thus is mandatory."
+            exit 4
+        fi
+    fi
+
+    # Dependencies
+    brew install ldid xz && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 6)
+
+    # Check for $THEOS env var
+    update "Checking for \$THEOS environment variable..."
+    if [[ "$THEOS" ]]; then
+        update "\$THEOS is already set to '$THEOS'. Nothing to do here."
+    else
+        update "\$THEOS has not been set. Setting now..."
+
+        SHELL_ENV="unknown"
+        common "SHELL IS $CSHELL and shell env is $SHELL_ENV."
+        if [[ "${CSHELL,,}" == "bash" ]]; then
+            SHELL_ENV="~/.profile"
+        elif [[ "${CSHELL,,}" == "zsh" ]]; then
+            SHELL_ENV="~/.zshenv"
+        else
+            error "Current shell is unsupported by this installer. Please set the THEOS environment variable to '~/theos' manually before proceeding."
+            exit 7
+        fi
+
+        # Set $THEOS
+        echo "export THEOS=~/theos" >> "$SHELL_ENV"
+        source "$SHELL_ENV"
+        if [[ "$THEOS" ]]; then
+            update "\$THEOS has been successfully set to '$THEOS'!"
+        else
+            error "\$THEOS is still not set despite our efforts. Try restarting your shell and/or running the installer again. If that doesn't do the trick, you may have to set the THEOS environment variable to '~/theos' manually before proceeding."
+            exit 8
+        fi
+    fi
+
+    # Get Theos
+    update "Checking for Theos install..."
+    if [[ -d "$THEOS" && "$(ls -A "$THEOS")" ]]; then
+        update "Theos appears to already be installed. Checking for updates..."
+        $THEOS/bin/update-theos
+    else
+        update "Theos does not appear to be installed. Cloning now..."
+        git clone --recursive https://github.com/theos/theos.git $THEOS
+    fi
+
+    # Get patched sdks
+    update "Checking for patched sdks..."
+    if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/")" ]]; then
+        update "SDKs appear to already be installed."
+    else
+        update "SDKS do not appear to be installed. Installing now..."
+        curl -LO https://github.com/theos/sdks/archive/master.zip
+        TMP=$(mktemp -d)
+        unzip master.zip -d $TMP
+        mv $TMP/sdks-master/*.sdk $THEOS/sdks
+        rm -r master.zip $TMP
+
+        if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/")" ]]; then
+            update "SDKs successfully installed!"
+        else
+            error "Something appears to have gone wrong. Please try again."
+            exit 9
+        fi
+    fi
 }
 
 darwin-mobile() {
     common "Platform: Darwin (Mobile)"
 
     # Check for sudo (not installed by default on some jbs)
-    read -p "Do you have 'sudo' installed'? [y/n]" check
-    if [[ "${check,,}" = "y" || "${check,,}" = "yes" ]]; then
-        common "Great! Continuing with installation..."
-    else
+    if ! command -v sudo &> /dev/null; then
         error "Please install 'sudo' in your package manager before proceeding with the installation."
         exit 3
     fi
