A couple more linux things

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -33,9 +33,9 @@ PLATFORM=$(uname)
 CSHELL=$(ps -p $$ | tail -1 | grep -o '[^ ]*$' | sed 's/[^[:alpha:]]//g')
 SHELL_ENV="unknown"
 if [[ "${CSHELL,,}" == "bash" ]]; then
-    SHELL_ENV="~/.profile"
+    SHELL_ENV="$HOME/.profile"
 elif [[ "${CSHELL,,}" == "zsh" ]]; then
-    SHELL_ENV="~/.zshenv"
+    SHELL_ENV="$HOME/.zshenv"
 fi
 # TODO: CI support (non-interactive)
 NONINTERACTIVE=0
@@ -265,7 +265,7 @@ linux() {
     # Dependencies
     update "Preparing to install dependencies. Please enter your password if prompted:"
     if [[ "${DISTRO,,}" == "debian" ]]; then
-        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libxml2 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
     fi
 
     # Check for WSL
