move swift support into 64-bit only

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -299,24 +299,24 @@ darwin_mobile() {
 				exit 3
 			fi
 		fi
-	fi
-
-	# Check desire for Swift support
-	update "Checking desire for Swift support..."
-	read -p "Would you like to be able to work with Swift? If so, an additional package will need to be installed. [y/n]" confirm
-	if theos_bool $confirm; then
-		if [[ -f /.procursus_strapped || -f /var/jb/.procursus_strapped ]]; then
-			sudo apt install -y "${iFLAGS[@]}" swift \
-				&& update "Additional Swift package installation successful!" \
-				|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
+		
+		# Check desire for Swift support
+		update "Checking desire for Swift support..."
+		read -p "Would you like to be able to work with Swift? If so, an additional package will need to be installed. [y/n]" confirm
+		if theos_bool $confirm; then
+			if [[ -f /.procursus_strapped || -f /var/jb/.procursus_strapped ]]; then
+				sudo apt install -y "${iFLAGS[@]}" swift \
+					&& update "Additional Swift package installation successful!" \
+					|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
+			else
+				sudo apt install -y "${iFLAGS[@]}" com.kabiroberai.swift-toolchain \
+					&& update "Additional Swift package installation successful!" \
+					|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
+			fi
 		else
-			sudo apt install -y "${iFLAGS[@]}" com.kabiroberai.swift-toolchain \
-				&& update "Additional Swift package installation successful!" \
-				|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
+			update "Skipping Swift support."
+			common "Note: if you end up wanting to use Swift in the future, just install the 'swift' (Procursus ONLY) or 'swift-toolchain' (all other bootstraps) packages from within your package manager."
 		fi
-	else
-		update "Skipping Swift support."
-		common "Note: if you end up wanting to use Swift in the future, just install the 'swift' (Procursus ONLY) or 'swift-toolchain' (all other bootstraps) packages from within your package manager."
 	fi
 
 	set_theos
