More fixes

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -32,7 +32,7 @@ fi
 PLATFORM=$(uname)
 CSHELL="${SHELL##*/}"
 SHELL_ENV="unknown"
-if [[ "${CSHELL,,}" == "bash" ]]; then
+if [[ "${CSHELL,,}" == "sh" || "${CSHELL,,}" == "bash" ]]; then
     SHELL_ENV="$HOME/.profile"
 elif [[ "${CSHELL,,}" == "zsh" ]]; then
     SHELL_ENV="$HOME/.zshenv"
@@ -145,7 +145,7 @@ darwin-mobile() {
     if [[ $OLD == 1 ]]; then
         read -p "Do you have 'https://coolstar.org/publicrepo/', 'https://repo.bingner.com/', and 'http://apt.thebigboss.org/repofiles/cydia/' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
         if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
-            sudo apt install org.theos.dependencies -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
+            sudo apt install org.theos.dependencies -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
         else
             error "Please install the repos mentioned above before proceeding."
             exit 4
@@ -155,7 +155,7 @@ darwin-mobile() {
         if [[ -f "/.procursus_strapped" ]]; then
             read -p "Do you have 'https://apt.procursus.us' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
             if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
-                sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl plutil rsync unzip xz-utils -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
+                sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl plutil rsync unzip xz-utils -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
             else
                 error "Please install the repo mentioned above before proceeding."
                 exit 4
@@ -163,7 +163,7 @@ darwin-mobile() {
         else
             read -p "Do you have 'https://apt.bingner.com' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
             if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
-                sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync unzip xz -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
+                sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync unzip xz -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 5)
             else
                 error "Please install the repo mentioned above before proceeding."
                 exit 4
@@ -176,9 +176,9 @@ darwin-mobile() {
     read -p "Would you like to be able to work with Swift? If so, an additional package will need to be installed. [y/n]" confirm
     if [[ "${confirm,,}" == "y" || "${confirm,,}" == "yes" ]]; then
         if [[ -f "/.procursus_strapped" ]]; then
-            sudo apt install swift -y && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 4)
+            sudo apt install swift -y --allow-unauthenticated --allow-downgrades && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 4)
         else
-            sudo apt install swift-toolchain -y && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 4)
+            sudo apt install com.kabiroberai.swift-toolchain -y --allow-unauthenticated --allow-downgrades && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 4)
         fi
     else
         update "Skipping Swift support."
@@ -198,15 +198,15 @@ darwin-mobile() {
         fi
 
         # Set $THEOS
-        if [[ -f /var/checkra1n.dmg || -d /binpack ]]; then
+        if [[ -f /.bootstrapped ]]; then
             # checkra1n has no exec in var, so need to set
             #  up '/opt' for use with Theos as mobile user
             echo "export THEOS=/opt/theos" >> "$SHELL_ENV"
             if [[ -d "/opt" ]]; then
                 update "'/opt' already exists. Checking its ownership..."
                 # Check that '/opt' isn't owned by root
-                STATUS="$(stat -c '%U' /opt)"
-                if [[ "${status,,}" == "root" ]]; then
+                OWNER="$(stat -c '%U' /opt)"
+                if [[ "${OWNER,,}" == "root" ]]; then
                     update "Owner of '/opt' is root. Attempting to switch owner to mobile..."
                     sudo chown mobile /opt && update "Owner of '/opt' successfully transfered to mobile from root!" || (error "Failed to transfer ownership of '/opt' to mobile from root. Please see the log above." && exit 7)
                 fi
@@ -272,7 +272,7 @@ linux() {
         git clone https://aur.archlinux.org/ncurses5-compat-libs.git
         cd ncurses5-compat-libs
         gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
-        makepkg -sir --noconfirm
+        makepkg -sir --noconfirm && cd .. && rm -r ncurses5-compat-libs
     fi
 
     # Check for WSL
@@ -335,7 +335,11 @@ linux() {
             if [[ "${stoolchain,,}" == "y" || "${stoolchain,,}" == "yes" ]]; then
                 read -p "You chose to install the Swift-compatible toolchain. Is this correct? [y/n]" confirm
                 if [[ "${confirm,,}" == "y" || "${confirm,,}" == "yes" ]]; then
-                    sudo apt install zstd -y
+                    if [[ "${DISTRO,,}" == "debian" ]]; then
+                        sudo apt install zstd -y
+                    elif [[ "${DISTRO,,}" == "arch" ]]; then
+                        sudo pacman -S --noconfirm zstd
+                    fi
                     curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
                     TMP=$(mktemp -d)
                     tar -xvf swift-5.3.2-RELEASE-ubuntu20.04.tar.zst -C $TMP
