Fix a couple things

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -273,7 +273,7 @@ linux() {
 	if [[ "${DISTRO,,}" == "debian" ]]; then
 		sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
 	elif [[ "${DISTRO,,}" == "arch" ]]; then
-		sudo pacman -S --needed --noconfirm base-devel fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
 		# libtinfo5 equivalent (get from AUR)
 		if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
 			git clone https://aur.archlinux.org/ncurses5-compat-libs.git
@@ -282,14 +282,14 @@ linux() {
 			MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm && cd .. && rm -rf ncurses5-compat-libs
 		fi
 		# libz3-dev equivalent is z3 and we need to create lib version queried
-		sudo ln -sf /usr/lib/libz3.so.4.8 /usr/lib/libz3.so.4
+		sudo ln -sf /usr/lib/libz3.so.4.8 /usr/lib/libz3.so.4 # NOT PORTABLE
 	elif [[ "${DISTRO,,}" == "fedora" ]]; then
 		sudo dnf group install -y "C Development Tools and Libraries" && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
-		sudo dnf install -y fakeroot z3-libs lzma libbsd rsync curl perl unzip git && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		sudo dnf install -y fakeroot z3-libs lzma libbsd rsync curl perl unzip git && update "Other dependencies have been successfully installed!" || (error "Other dependency install command seems to have encountered an error. Please see the log above." && exit 4)
 		# create libtinfo version queried
 		sudo ln -sf /usr/lib64/libtinfo.so.6.* /usr/lib64/libtinfo.so.5
 		# libz3-dev equivalent is z3-libs and we need to create lib version queried
-		sudo ln -sf /usr/lib64/libz3.so.4.8 /usr/lib64/libz3.so.4
+		sudo ln -sf /usr/lib64/libz3.so.4.8 /usr/lib64/libz3.so.4 # NOT PORTABLE
 	fi
 
 	# Check for WSL
