Didn't need the additional dep (already installed) + clarify post-install

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -265,7 +265,7 @@ linux() {
     # Dependencies
     update "Preparing to install dependencies. Please enter your password if prompted:"
     if [[ "${DISTRO,,}" == "debian" ]]; then
-        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libxml2 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
     fi
 
     # Check for WSL
@@ -401,11 +401,11 @@ if [[ "${PLATFORM,,}" == "darwin" ]]; then
     else
         darwin
     fi
-    special "Theos has been successfully installed! Run \$THEOS/bin/nic.pl to get started."
+    special "Theos has been successfully installed! Restart your shell and then run \$THEOS/bin/nic.pl to get started."
 elif [[ "${PLATFORM,,}" == "linux" ]]; then
     special "starting install..."
     linux
-    special "Theos has been successfully installed! Run \$THEOS/bin/nic.pl to get started."
+    special "Theos has been successfully installed! Restart your shell and then run \$THEOS/bin/nic.pl to get started."
 else
     error "'$PLATFORM' is currently unsupported by this installer and/or Theos."
     exit 2
