Fedora works!

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -285,7 +285,11 @@ linux() {
 		sudo ln -sf /usr/lib/libz3.so.4.* /usr/lib/libz3.so.4
 	elif [[ "${DISTRO,,}" == "fedora" ]]; then
 		sudo dnf group install -y "C Development Tools and Libraries" && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
-		sudo dnf install -y fakeroot rsync curl perl unzip git && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		sudo dnf install -y fakeroot z3-libs lzma libbsd rsync curl perl unzip git && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		# create libtinfo version queried
+		sudo ln -sf /usr/lib64/libtinfo.so.6.* /usr/lib64/libtinfo.so.5
+		# libz3-dev equivalent is z3-libs and we need to create lib version queried
+		sudo ln -sf /usr/lib64/libz3.so.4.8 /usr/lib64/libz3.so.4
 	fi
 
 	# Check for WSL
