Make '&&' and '||' lines multiline

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -75,7 +75,9 @@ get-theos() {
 		$THEOS/bin/update-theos
 	else
 		update "Theos does not appear to be installed. Cloning now..."
-		git clone --recursive https://github.com/theos/theos.git $THEOS && update "Git clone of Theos was successful!" || (error "Theos git clone command seems to have encountered an error. Please see the log above." && exit 6)
+		git clone --recursive https://github.com/theos/theos.git $THEOS \
+			&& update "Git clone of Theos was successful!" \
+			|| (error "Theos git clone command seems to have encountered an error. Please see the log above."; exit 6)
 	fi
 }
 
@@ -114,7 +116,9 @@ darwin() {
 	if ! [[ -x $(command -v brew) ]]; then
 		read -p "Homebrew, which provides tools Theos depends on, is not installed. Would you like to have it installed for you? [y/n]" hbrew
 		if theos-bool $hbrew; then
-			bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && update "Homebrew has been successfully installed!" || (error "Homebrew install command seems to have encountered an error. Please see the log above." && exit 3)
+			bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
+				&& update "Homebrew has been successfully installed!" \
+				|| (error "Homebrew install command seems to have encountered an error. Please see the log above."; exit 3)
 		else
 			error "Homebrew provides tools Theos depends on and thus is mandatory. Please install Homebrew before proceeding with the installation."
 			exit 3
@@ -122,7 +126,9 @@ darwin() {
 	fi
 
 	# Dependencies
-	brew install ldid xz && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+	brew install ldid xz \
+		&& update "Dependencies have been successfully installed!" \
+		|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 
 	# Check for $THEOS env var
 	update "Checking for \$THEOS environment variable..."
@@ -172,7 +178,9 @@ darwin-mobile() {
 	if [[ $OLD -eq 1 ]]; then
 		read -p "Do you have 'https://coolstar.org/publicrepo/', 'https://repo.bingner.com/', and 'http://apt.thebigboss.org/repofiles/cydia/' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
 		if theos-bool $ready ]]; then
-			sudo apt install org.theos.dependencies -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+			sudo apt install org.theos.dependencies -y --allow-unauthenticated --allow-downgrades \
+				&& update "Dependencies have been successfully installed!" \
+				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 		else
 			error "Please install the repos mentioned above before proceeding."
 			exit 3
@@ -182,7 +190,9 @@ darwin-mobile() {
 		if [[ -f /.procursus_strapped ]]; then
 			read -p "Do you have 'https://apt.procursus.us' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
 			if theos-bool $ready; then
-				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl plutil rsync unzip xz-utils -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl plutil rsync unzip xz-utils -y --allow-unauthenticated --allow-downgrades \
+					&& update "Dependencies have been successfully installed!" \
+					|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 			else
 				error "Please install the repo mentioned above before proceeding."
 				exit 3
@@ -190,7 +200,9 @@ darwin-mobile() {
 		else
 			read -p "Do you have 'https://apt.bingner.com' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
 			if theos-bool $ready; then
-				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync unzip xz -y --allow-unauthenticated --allow-downgrades && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync unzip xz -y --allow-unauthenticated --allow-downgrades \
+					&& update "Dependencies have been successfully installed!" \
+					|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 			else
 				error "Please install the repo mentioned above before proceeding."
 				exit 3
@@ -203,9 +215,13 @@ darwin-mobile() {
 	read -p "Would you like to be able to work with Swift? If so, an additional package will need to be installed. [y/n]" confirm
 	if theos-bool $confirm; then
 		if [[ -f /.procursus_strapped ]]; then
-			sudo apt install swift -y --allow-unauthenticated --allow-downgrades && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 3)
+			sudo apt install swift -y --allow-unauthenticated --allow-downgrades \
+				&& update "Additional Swift package installation successful!" \
+				|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
 		else
-			sudo apt install com.kabiroberai.swift-toolchain -y --allow-unauthenticated --allow-downgrades && update "Additional Swift package installation successful!" || (error "Additional Swift package install command seems to have encountered an error. Please see the log above." && exit 3)
+			sudo apt install com.kabiroberai.swift-toolchain -y --allow-unauthenticated --allow-downgrades \
+				&& update "Additional Swift package installation successful!" \
+				|| (error "Additional Swift package install command seems to have encountered an error. Please see the log above."; exit 3)
 		fi
 	else
 		update "Skipping Swift support."
@@ -236,11 +252,15 @@ darwin-mobile() {
 				OWNER="$(stat -c '%U' /opt)"
 				if [[ ${OWNER,,} == root ]]; then
 					update "Owner of '/opt' is root. Attempting to switch owner to mobile..."
-					sudo chown mobile /opt && update "Owner of '/opt' successfully transfered to mobile from root!" || (error "Failed to transfer ownership of '/opt' to mobile from root. Please see the log above." && exit 9)
+					sudo chown mobile /opt \
+						&& update "Owner of '/opt' successfully transfered to mobile from root!" \
+						|| (error "Failed to transfer ownership of '/opt' to mobile from root. Please see the log above."; exit 9)
 				fi
 			else
 				update "Creating a special directory to house Theos..."
-				sudo install -d -o mobile -g mobile /opt && update "Special directory for Theos created successfully!" || (error "Special directory create command seems to have encountered an error. Please see the log above." && exit 9)
+				sudo install -d -o mobile -g mobile /opt \
+					&& update "Special directory for Theos created successfully!" \
+					|| (error "Special directory create command seems to have encountered an error. Please see the log above."; exit 9)
 			fi
 		else
 			echo "export THEOS=~/theos" >> "$SHELL_ENV"
@@ -280,28 +300,42 @@ linux() {
 	# Dependencies
 	update "Preparing to install dependencies. Please enter your password if prompted:"
 	if [[ $DISTRO == debian ]]; then
-		sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+		sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y \
+			&& update "Dependencies have been successfully installed!" \
+			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 	elif [[ $DISTRO == arch ]]; then
-		sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+		sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl unzip git z3 -y \
+			&& update "Dependencies have been successfully installed!" \
+			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 		# libtinfo5 equivalent (get from AUR)
 		if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
 			git clone https://aur.archlinux.org/ncurses5-compat-libs.git
 			cd ncurses5-compat-libs
 			gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
-			MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm && cd .. && rm -rf ncurses5-compat-libs
+			MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm \
+				&& cd .. \
+				&& rm -rf ncurses5-compat-libs
 		fi
 		# libz3-dev equivalent is z3 and we need to create lib version queried
 		LATEST_LIBZ3="$(ls -v /usr/lib/ | grep libz3 | tail -n 1)"
 		sudo ln -sf /usr/lib/$LATEST_LIBZ3 /usr/lib/libz3.so.4
 	elif [[ $DISTRO == redhat ]]; then
-		sudo dnf group install -y "C Development Tools and Libraries" && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
-		sudo dnf install -y fakeroot z3-libs ncurses-compat-libs lzma libbsd rsync curl perl unzip git && update "Other dependencies have been successfully installed!" || (error "Other dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+		sudo dnf group install -y "C Development Tools and Libraries" \
+			&& update "Dependencies have been successfully installed!" \
+			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+		sudo dnf install -y fakeroot z3-libs ncurses-compat-libs lzma libbsd rsync curl perl unzip git \
+			&& update "Other dependencies have been successfully installed!" \
+			|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 		# libz3-dev equivalent is z3-libs and we need to create lib version queried
 		LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
 		sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
 	elif [[ $DISTRO == suse ]]; then
-		sudo zypper install -y -t pattern devel_basis && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
-		sudo zypper install -y fakeroot libz3-4_8 libbsd0 libncurses5 rsync curl perl unzip git && update "Other dependencies have been successfully installed!" || (error "Other dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+		sudo zypper install -y -t pattern devel_basis \
+			&& update "Dependencies have been successfully installed!" \
+			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+		sudo zypper install -y fakeroot libz3-4_8 libbsd0 libncurses5 rsync curl perl unzip git \
+			&& update "Other dependencies have been successfully installed!" \
+			|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 		# libz3-dev equivalent is libz3-4_8 and we need to create lib version queried
 		LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
 		sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
@@ -316,7 +350,9 @@ linux() {
 		VERSION=$(uname -r | sed 's/.*\([[:digit:]]\)[[:space:]]*/\1/')
 		if [[ $VERSION -eq 1 ]]; then
 			update "WSL1! Need to fix fakeroot..."
-			sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp && update "fakeroot fixed!" || (error "fakeroot fix seems to have encountered an error. Please see the log above." && exit 10)
+			sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp \
+				&& update "fakeroot fixed!" \
+				|| (error "fakeroot fix seems to have encountered an error. Please see the log above."; exit 10)
 		else
 			update "WSL2! Nothing to do here."
 		fi
@@ -407,13 +443,17 @@ freebsd() {
 
 	# Dependencies
 	update "Preparing to install dependencies. Please enter your password if prompted:"
-	sudo pkg install -y bash curl gmake ncurses fakeroot git rsync curl unzip && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+	sudo pkg install -y bash curl gmake ncurses fakeroot git rsync curl unzip \
+		&& update "Dependencies have been successfully installed!" \
+		|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
 
 	# Enable linux binary compatibility
 	update "Enabling Linux binary compatibility..."
 	sudo sysrc linux_enable=YES
 	sudo service linux start
-	sudo pkg install -y linux_base-c7 && update "Linux binary compatibility successfully enabled!" || (error "Linux binary compatibility command seems to have encountered an error. Please see the log above." && exit 11)
+	sudo pkg install -y linux_base-c7 \
+		&& update "Linux binary compatibility successfully enabled!" \
+		|| (error "Linux binary compatibility command seems to have encountered an error. Please see the log above."; exit 11)
 
 	# Compatibility with common Theos commands
 	echo "alias make=gmake" >> "$SHELL_ENV"
