Add FreeBSD support to install-theos

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -260,14 +260,20 @@ darwin-mobile() {
 linux() {
     common "Platform: Linux"
 
+    # Check for sudo (not installed by default on some distros)
+    if ! command -v sudo &> /dev/null; then
+        error "Please install 'sudo' before proceeding with the installation."
+        exit 3
+    fi
+
     DISTRO="$(cat /etc/*release | grep "^ID=" | sed -e "s/^ID=//")"
 
     # Dependencies
     update "Preparing to install dependencies. Please enter your password if prompted:"
     if [[ "${DISTRO,,}" == "debian" ]]; then
-        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
     elif [[ "${DISTRO,,}" == "arch" ]]; then
-        sudo pacman -S --needed --noconfirm base-devel fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        sudo pacman -S --needed --noconfirm base-devel fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
         # libtinfo5 equivalent (get from AUR)
         if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
             git clone https://aur.archlinux.org/ncurses5-compat-libs.git
@@ -285,13 +291,140 @@ linux() {
         VERSION=$(uname -r | sed 's/.*\([[:digit:]]\)[[:space:]]*/\1/')
         if [[ $VERSION == 1 ]]; then
             update "WSL1! Need to fix fakeroot..."
-            sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp && update "fakeroot fixed!" || (error "fakeroot fix seems to have encountered an error. Please see the log above." && exit 4)
+            sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp && update "fakeroot fixed!" || (error "fakeroot fix seems to have encountered an error. Please see the log above." && exit 5)
         else
             update "WSL2! Nothing to do here."
         fi
     else
         update "Seems you're not using WSL. Moving on..."
     fi
+
+    # Check for $THEOS env var
+    update "Checking for \$THEOS environment variable..."
+    if [[ "$THEOS" ]]; then
+        update "\$THEOS is already set to '$THEOS'. Nothing to do here."
+    else
+        update "\$THEOS has not been set. Setting now..."
+
+        if [[ "${CSHELL,,}" == "unknown" ]]; then
+            error "Current shell ($CSHELL) is unsupported by this installer. Please set the THEOS environment variable to '~/theos' manually before proceeding."
+            exit 6
+        fi
+
+        # Set $THEOS and prioritize $THEOS/toolchain
+        echo "export THEOS=~/theos" >> "$SHELL_ENV"
+        echo 'export PATH=$THEOS/toolchain/linux/iphone/bin:$PATH' >> "$SHELL_ENV"
+        echo 'export LD_LIBRARY_PATH=$THEOS/toolchain/linux/iphone/lib:$LD_LIBRARY_PATH' >> "$SHELL_ENV"
+        source "$SHELL_ENV"
+        if [[ "$THEOS" ]]; then
+            update "\$THEOS has been successfully set to '$THEOS'!"
+        else
+            error "\$THEOS is still not set despite our efforts. Try restarting your shell and/or running the installer again. If that doesn't do the trick, you may have to set the THEOS environment variable to '~/theos' manually before proceeding."
+            exit 7
+        fi
+    fi
+
+    # Get Theos
+    update "Checking for Theos install..."
+    if [[ -d "$THEOS" && "$(ls -A "$THEOS")" ]]; then
+        update "Theos appears to already be installed. Checking for updates..."
+        $THEOS/bin/update-theos
+    else
+        update "Theos does not appear to be installed. Cloning now..."
+        git clone --recursive https://github.com/theos/theos.git $THEOS && update "Git clone of Theos was successful!" || (error "Theos git clone command seems to have encountered an error. Please see the log above." && exit 8)
+    fi
+
+    # Get a toolchain
+    update "Checking for iOS toolchain..."
+    if [[ -d "$THEOS/toolchain/linux/iphone/" && "$(ls -A "$THEOS/toolchain/linux/iphone")" ]]; then
+        update "A toolchain appears to already be installed."
+    else
+        while true; do
+            update "A toolchain does not appear to be installed."
+            read -p "Would you like your toolchain to support Swift (larger toolchain size) or not (smaller toolchain size)? [y/n]" stoolchain
+            if [[ "${stoolchain,,}" == "y" || "${stoolchain,,}" == "yes" ]]; then
+                read -p "You chose to install the Swift-compatible toolchain. Is this correct? [y/n]" confirm
+                if [[ "${confirm,,}" == "y" || "${confirm,,}" == "yes" ]]; then
+                    if [[ "${DISTRO,,}" == "debian" ]]; then
+                        sudo apt install zstd -y
+                    elif [[ "${DISTRO,,}" == "arch" ]]; then
+                        sudo pacman -S --needed --noconfirm zstd
+                    fi
+                    curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
+                    TMP=$(mktemp -d)
+                    tar -xvf swift-5.3.2-RELEASE-ubuntu20.04.tar.zst -C $TMP
+                    mkdir -p $THEOS/toolchain/linux/iphone $THEOS/toolchain/swift
+                    mv $TMP/swift-5.3.2-RELEASE-ubuntu20.04/* $THEOS/toolchain/linux/iphone/
+                    ln -s $THEOS/toolchain/linux/iphone $THEOS/toolchain/swift
+                    rm -r swift-5.3.2-RELEASE-ubuntu20.04.tar.zst $TMP
+
+                    # Confirm that toolchain is usable
+                    if command -v otool &> /dev/null; then
+                        update "Successfully installed the Swift-compatible toolchain!"
+                    else
+                        error "Something appears to have gone wrong -- the toolchain is not accessible. Please try again."
+                        exit 9
+                    fi
+                    break
+                fi
+            elif [[ "${stoolchain,,}" == "n" || "${stoolchain,,}" == "no" ]]; then
+                read -p "You chose to install the non-Swift-compatible toolchain. Is this correct? [y/n]" confirm
+                if [[ "${confirm,,}" == "y" || "${confirm,,}" == "yes" ]]; then
+                    curl -LO https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
+                    TMP=$(mktemp -d)
+                    tar -xvf linux-ios-arm64e-clang-toolchain.tar.lzma -C $TMP
+                    mkdir -p $THEOS/toolchain/linux/iphone
+                    mv $TMP/ios-arm64e-clang-toolchain/* $THEOS/toolchain/linux/iphone/
+                    rm -r linux-ios-arm64e-clang-toolchain.tar.lzma $TMP
+
+                    # Confirm that toolchain is usable
+                    if command -v otool &> /dev/null; then
+                        update "Successfully installed the non-Swift-compatible toolchain!"
+                    else
+                        error "Something appears to have gone wrong -- the toolchain is not accessible. Please try again."
+                        exit 9
+                    fi
+                    break
+                fi
+            else
+                common "Please pick your desired toolchain to continue."
+            fi
+        done
+    fi
+
+    # Get patched sdks
+    update "Checking for patched sdks..."
+    if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/" | grep sdk)" ]]; then
+        update "SDKs appear to already be installed."
+    else
+        update "SDKS do not appear to be installed. Installing now..."
+        curl -LO https://github.com/theos/sdks/archive/master.zip
+        TMP=$(mktemp -d)
+        unzip master.zip -d $TMP
+        mv $TMP/sdks-master/*.sdk $THEOS/sdks
+        rm -r master.zip $TMP
+
+        if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/" | grep sdk)" ]]; then
+            update "SDKs successfully installed!"
+        else
+            error "Something appears to have gone wrong. Please try again."
+            exit 10
+        fi
+    fi
+}
+
+freebsd() {
+    common "Platform: FreeBSD"
+
+    # Check for sudo (not installed by default)
+    if ! command -v sudo &> /dev/null; then
+        error "Please install 'sudo' before proceeding with the installation."
+        exit 3
+    fi
+
+    # Dependencies
+    update "Preparing to install dependencies. Please enter your password if prompted:"
+    sudo pkg install -y bash fakeroot git rsync curl unzip && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
 
     # Check for $THEOS env var
     update "Checking for \$THEOS environment variable..."
@@ -339,11 +472,7 @@ linux() {
             if [[ "${stoolchain,,}" == "y" || "${stoolchain,,}" == "yes" ]]; then
                 read -p "You chose to install the Swift-compatible toolchain. Is this correct? [y/n]" confirm
                 if [[ "${confirm,,}" == "y" || "${confirm,,}" == "yes" ]]; then
-                    if [[ "${DISTRO,,}" == "debian" ]]; then
-                        sudo apt install zstd -y
-                    elif [[ "${DISTRO,,}" == "arch" ]]; then
-                        sudo pacman -S --needed --noconfirm zstd
-                    fi
+                    sudo pkg install -y zstd
                     curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
                     TMP=$(mktemp -d)
                     tar -xvf swift-5.3.2-RELEASE-ubuntu20.04.tar.zst -C $TMP
@@ -420,6 +549,10 @@ if [[ "${PLATFORM,,}" == "darwin" ]]; then
 elif [[ "${PLATFORM,,}" == "linux" ]]; then
     special "starting install..."
     linux
+    special "Theos has been successfully installed! Restart your shell and then run \$THEOS/bin/nic.pl to get started."
+elif [[ "${PLATFORM,,}" == "freebsd" ]]; then
+    special "starting install..."
+    freebsd
     special "Theos has been successfully installed! Restart your shell and then run \$THEOS/bin/nic.pl to get started."
 else
     error "'$PLATFORM' is currently unsupported by this installer and/or Theos."
