Add (incomplete) Fedora compatibility to install-theos

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -283,6 +283,9 @@ linux() {
         fi
         # libz3-dev equivalent is z3 and we need to create lib version queried
         sudo ln -sf /usr/lib/libz3.so.4.* /usr/lib/libz3.so.4
+	elif [[ "${DISTRO,,}" == "fedora" ]]; then
+		sudo dnf group install -y "C Development Tools and Libraries" && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		sudo dnf install -y fakeroot rsync curl perl unzip git && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
     fi
 
     # Check for WSL
@@ -349,6 +352,8 @@ linux() {
                         sudo apt install zstd -y
                     elif [[ "${DISTRO,,}" == "arch" ]]; then
                         sudo pacman -S --needed --noconfirm zstd
+                    elif [[ "${DISTRO,,}" == "fedora" ]]; then
+						sudo dnf install -y zstd
                     fi
                     curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
                     TMP=$(mktemp -d)
