Improve legibility of Linux dep install section?

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -295,54 +295,60 @@ linux() {
 
 	# Dependencies
 	update "Preparing to install dependencies. Please enter your password if prompted:"
-	if [[ $DISTRO == debian ]]; then
-		sudo apt update
-		sudo apt install -y build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libxml2 \
-			&& update "Dependencies have been successfully installed!" \
-			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-	elif [[ $DISTRO == arch ]]; then
-		sudo pacman -Syy
-		sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl unzip git libxml2 z3 \
-			&& update "Dependencies have been successfully installed!" \
-			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-		# libtinfo5 equivalent (get from AUR)
-		if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
-			git clone https://aur.archlinux.org/ncurses5-compat-libs.git
-			cd ncurses5-compat-libs
-			gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
-			MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm \
-				&& cd .. \
-				&& rm -rf ncurses5-compat-libs
-		fi
-		# libz3-dev equivalent is z3 and we need to create lib version queried
-		LATEST_LIBZ3="$(ls -v /usr/lib/ | grep libz3 | tail -n 1)"
-		sudo ln -sf /usr/lib/$LATEST_LIBZ3 /usr/lib/libz3.so.4
-	elif [[ $DISTRO == redhat ]]; then
-		sudo dnf check-update
-		sudo dnf group install -y "C Development Tools and Libraries" \
-			&& update "Dependencies have been successfully installed!" \
-			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-		sudo dnf install -y fakeroot z3-libs ncurses-compat-libs lzma libbsd rsync curl perl unzip git libxml2 \
-			&& update "Other dependencies have been successfully installed!" \
-			|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-		# libz3-dev equivalent is z3-libs and we need to create lib version queried
-		LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
-		sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
-	elif [[ $DISTRO == suse ]]; then
-		sudo zypper refresh
-		sudo zypper install -y -t pattern devel_basis \
-			&& update "Dependencies have been successfully installed!" \
-			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-		sudo zypper install -y fakeroot libz3-4_8 libbsd0 libncurses5 rsync curl perl unzip git libxml2 \
-			&& update "Other dependencies have been successfully installed!" \
-			|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
-		# libz3-dev equivalent is libz3-4_8 and we need to create lib version queried
-		LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
-		sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
-	else
-		error "The dependencies for your distro are unknown to this installer. Note that they will need to be determined before Theos can be installed and/or function properly."
-		common "On Debian-based distros, the necessary dependencies are: build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git. Additional dependencies may also be required depending on what your distro provides."
-	fi
+	case $DISTRO in
+		debian)
+			sudo apt update
+			sudo apt install -y build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libxml2 \
+				&& update "Dependencies have been successfully installed!" \
+				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			;;
+		arch)
+			sudo pacman -Syy
+			sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl unzip git libxml2 z3 \
+				&& update "Dependencies have been successfully installed!" \
+				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			# libtinfo5 equivalent (get from AUR)
+			if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
+				git clone https://aur.archlinux.org/ncurses5-compat-libs.git
+				cd ncurses5-compat-libs
+				gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
+				MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm \
+					&& cd .. \
+					&& rm -rf ncurses5-compat-libs
+			fi
+			# libz3-dev equivalent is z3 and we need to create lib version queried
+			LATEST_LIBZ3="$(ls -v /usr/lib/ | grep libz3 | tail -n 1)"
+			sudo ln -sf /usr/lib/$LATEST_LIBZ3 /usr/lib/libz3.so.4
+			;;
+		redhat)
+			sudo dnf check-update
+			sudo dnf group install -y "C Development Tools and Libraries" \
+				&& update "Dependencies have been successfully installed!" \
+				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			sudo dnf install -y fakeroot z3-libs ncurses-compat-libs lzma libbsd rsync curl perl unzip git libxml2 \
+				&& update "Other dependencies have been successfully installed!" \
+				|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			# libz3-dev equivalent is z3-libs and we need to create lib version queried
+			LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
+			sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
+			;;
+		suse)
+			sudo zypper refresh
+			sudo zypper install -y -t pattern devel_basis \
+				&& update "Dependencies have been successfully installed!" \
+				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			sudo zypper install -y fakeroot libz3-4_8 libbsd0 libncurses5 rsync curl perl unzip git libxml2 \
+				&& update "Other dependencies have been successfully installed!" \
+				|| (error "Other dependency install command seems to have encountered an error. Please see the log above."; exit 3)
+			# libz3-dev equivalent is libz3-4_8 and we need to create lib version queried
+			LATEST_LIBZ3="$(ls -v /usr/lib64/ | grep libz3 | tail -n 1)"
+			sudo ln -sf /usr/lib64/$LATEST_LIBZ3 /usr/lib64/libz3.so.4
+			;;
+		*)
+			error "The dependencies for your distro are unknown to this installer. Note that they will need to be determined before Theos can be installed and/or function properly."
+			common "On Debian-based distros, the necessary dependencies are: build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libxml2. Additional dependencies may also be required depending on what your distro provides."
+			;;
+	esac
 
 	# Check for WSL
 	update "Checking for WSL..."
