Arch support for install-theos

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -266,6 +266,13 @@ linux() {
     update "Preparing to install dependencies. Please enter your password if prompted:"
     if [[ "${DISTRO,,}" == "debian" ]]; then
         sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+    elif [[ "${DISTRO,,}" == "arch" ]]; then
+        sudo pacman -S --noconfirm base-devel fakeroot openssl rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        # libtinfo5 equivalent (get from AUR)
+        git clone https://aur.archlinux.org/ncurses5-compat-libs.git
+        cd ncurses5-compat-libs
+        gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
+        makepkg -sir --noconfirm
     fi
 
     # Check for WSL
