Add iOS support to 'install-theos'

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -34,6 +34,123 @@ darwin() {
 
 darwin-mobile() {
 	common "Platform: Darwin (Mobile)"
+
+	# Check for sudo (not installed by default on some jbs)
+	read -p "Do you have 'sudo' installed'? [y/n]" check
+	if [[ "${check,,}" = "y" || "${check,,}" = "yes" ]]; then
+		common "Great! Continuing with installation..."
+	else
+		error "Please install 'sudo' in your package manager before proceeding with the installation."
+		exit 2
+	fi
+
+	# Determine iOS version
+	OLD=0
+	KERNEL_VER=$(sysctl kern.osrelease | sed 's/[^0-9]*//g')
+	if [[ $KERNEL_VER < 1800 ]]; then
+		$OLD=1
+	fi
+
+	# Dependencies
+	update "Preparing to install dependencies. Please enter your password if prompted:"
+	if [[ $OLD == 1 ]]; then
+		read -p "Do you have 'https://coolstar.org/publicrepo/', 'https://repo.bingner.com/', and 'http://apt.thebigboss.org/repofiles/cydia/' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
+		if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
+			sudo apt install org.theos.dependencies -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+		else
+			error "Please install the repos mentioned above before proceeding."
+			exit 3
+		fi
+	else
+		# Dependencies pkg is outdated, so need to cater install for Procursus vs Elucubratus
+		if [[ -f "/.procursus_strapped" ]]; then
+			read -p "Do you have 'https://apt.procursus.us' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
+			if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
+				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl plutil rsync unzip xz-utils -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+			else
+				error "Please install the repo mentioned above before proceeding."
+				exit 3
+			fi
+		else
+			read -p "Do you have 'https://apt.bingner.com' installed in the sources of your jailbreak's primary package manager? [y/n]" ready
+			if [[ "${ready,,}" == "y" || "${ready,,}" == "yes" ]]; then
+				sudo apt install ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync unzip xz -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
+			else
+				error "Please install the repo mentioned above before proceeding."
+				exit 3
+			fi
+		fi
+	fi
+
+	# Check for $THEOS env var
+	update "Checking for \$THEOS environment variable..."
+	if [[ "$THEOS" ]]; then
+		update "\$THEOS is already set to '$THEOS'. Nothing to do here."
+	else
+		update "\$THEOS has not been set. Setting now..."
+
+		CSHELL=$(ps -p $$ | tail -1 | grep -o '[^ ]*$' | sed 's/[^[:alpha:]]//g')
+		SHELL_ENV="unknown"
+		common "SHELL IS $CSHELL and shell env is $SHELL_ENV."
+		if [[ "${CSHELL,,}" == "bash" ]]; then
+			SHELL_ENV="~/.profile"
+		elif [[ "${CSHELL,,}" == "zsh" ]]; then
+			SHELL_ENV="~/.zshenv"
+		else
+			error "Current shell is unsupported by this installer. Please set the THEOS environment variable to '~/theos' manually before proceeding."
+			exit 5
+		fi
+
+		# Set $THEOS
+		if [[ -f /var/checkra1n.dmg || -d /binpack ]]; then
+			# checkra1n has no exec in var, so need to set
+			#  up '/opt' for use with Theos as mobile user
+			echo "export THEOS=/opt/theos" >> "$SHELL_ENV"
+			sudo install -d -o mobile -g mobile /opt
+		else
+			echo "export THEOS=~/theos" >> "$SHELL_ENV"
+		fi
+		source "$SHELL_ENV"
+		if [[ "$THEOS" ]]; then
+			update "\$THEOS has been successfully set to '$THEOS'!"
+		else
+			error "\$THEOS is still not set despite our efforts. Try restarting your shell and/or running the installer again. If that doesn't do the trick, you may have to set the THEOS environment variable to '~/theos' manually before proceeding."
+			exit 6
+		fi
+	fi
+
+	# Get Theos
+	update "Checking for Theos install..."
+	if [[ -d "$THEOS" && "$(ls -A "$THEOS")" ]]; then
+		update "Theos appears to already be installed. Checking for updates..."
+		$THEOS/bin/update-theos
+	else
+		update "Theos does not appear to be installed. Cloning now..."
+		git clone --recursive https://github.com/theos/theos.git $THEOS
+	fi
+
+	# Note about Swift support
+	common "Please note: your install will *NOT* support Swift out-of-the-box. If you want to be able to work with Swift code, please install 'swift' (Procursus ONLY) or 'swift-toolchain' (all other bootstraps)."
+
+	# Get patched sdks
+	update "Checking for patched sdks..."
+	if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/")" ]]; then
+		update "SDKs appear to already be installed."
+	else
+		update "SDKS do not appear to be installed. Installing now..."
+		curl -LO https://github.com/theos/sdks/archive/master.zip
+		TMP=$(mktemp -d)
+		unzip master.zip -d $TMP
+		mv $TMP/sdks-master/*.sdk $THEOS/sdks
+		rm -r master.zip $TMP
+
+		if [[ -d "$THEOS/sdks/" && "$(ls -A "$THEOS/sdks/")" ]]; then
+			update "SDKs successfully installed!"
+		else
+			error "Something appears to have gone wrong. Please try again."
+			exit 7
+		fi
+	fi
 }
 
 linux() {
