Arch fixes

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -267,12 +267,16 @@ linux() {
     if [[ "${DISTRO,,}" == "debian" ]]; then
         sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
     elif [[ "${DISTRO,,}" == "arch" ]]; then
-        sudo pacman -S --noconfirm base-devel fakeroot openssl rsync curl perl unzip git -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
+        sudo pacman -S --needed --noconfirm base-devel fakeroot openssl rsync curl perl unzip git z3 -y && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 3)
         # libtinfo5 equivalent (get from AUR)
-        git clone https://aur.archlinux.org/ncurses5-compat-libs.git
-        cd ncurses5-compat-libs
-        gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
-        makepkg -sir --noconfirm && cd .. && rm -r ncurses5-compat-libs
+        if ! pacman -Qs ncurses5-compat-libs > /dev/null; then
+            git clone https://aur.archlinux.org/ncurses5-compat-libs.git
+            cd ncurses5-compat-libs
+            gpg --recv-keys "$(cat PKGBUILD | grep validpgp | grep -oP "(?<=').*(?=')")"
+            MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm && cd .. && rm -rf ncurses5-compat-libs
+        fi
+        # libz3-dev equivalent is z3 and we need to create lib version queried
+        sudo ln -sf /usr/lib/libz3.so.4.* /usr/lib/libz3.so.4
     fi
 
     # Check for WSL
@@ -338,7 +342,7 @@ linux() {
                     if [[ "${DISTRO,,}" == "debian" ]]; then
                         sudo apt install zstd -y
                     elif [[ "${DISTRO,,}" == "arch" ]]; then
-                        sudo pacman -S --noconfirm zstd
+                        sudo pacman -S --needed --noconfirm zstd
                     fi
                     curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
                     TMP=$(mktemp -d)
