A couple clarifications and minor fixes

diff --git a/bin/install-theos b/bin/install-theos
--- a/bin/install-theos
+++ b/bin/install-theos
@@ -266,6 +266,7 @@ linux() {
 		exit 3
 	fi
 
+	# TODO: make work for derivative distros
 	DISTRO="$(cat /etc/*release | grep "^ID=" | sed -e "s/^ID=//")"
 
 	# Dependencies
@@ -282,14 +283,18 @@ linux() {
 			MAKEFLAGS="-j$(nproc --all)" makepkg -sir --noconfirm && cd .. && rm -rf ncurses5-compat-libs
 		fi
 		# libz3-dev equivalent is z3 and we need to create lib version queried
-		sudo ln -sf /usr/lib/libz3.so.4.8 /usr/lib/libz3.so.4 # NOT PORTABLE
+		# TODO: make portable
+		sudo ln -sf /usr/lib/libz3.so.4.8 /usr/lib/libz3.so.4
 	elif [[ "${DISTRO,,}" == "fedora" ]]; then
 		sudo dnf group install -y "C Development Tools and Libraries" && update "Dependencies have been successfully installed!" || (error "Dependency install command seems to have encountered an error. Please see the log above." && exit 4)
-		sudo dnf install -y fakeroot z3-libs lzma libbsd rsync curl perl unzip git && update "Other dependencies have been successfully installed!" || (error "Other dependency install command seems to have encountered an error. Please see the log above." && exit 4)
-		# create libtinfo version queried
-		sudo ln -sf /usr/lib64/libtinfo.so.6.* /usr/lib64/libtinfo.so.5
+		sudo dnf install -y fakeroot z3-libs ncurses-compat-libs lzma libbsd rsync curl perl unzip git && update "Other dependencies have been successfully installed!" || (error "Other dependency install command seems to have encountered an error. Please see the log above." && exit 4)
 		# libz3-dev equivalent is z3-libs and we need to create lib version queried
-		sudo ln -sf /usr/lib64/libz3.so.4.8 /usr/lib64/libz3.so.4 # NOT PORTABLE
+		# TODO: make portable
+		sudo ln -sf /usr/lib64/libz3.so.4.8 /usr/lib64/libz3.so.4
+	else
+		error "The dependencies for $DISTRO are unknown. Note that these will need to be determined before Theos can be installed."
+		common "On Debian-based distros, the necessary dependencies are: build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git. Additional dependencies may also be required depending on what your distro provides."
+		exit 4
 	fi
 
 	# Check for WSL
@@ -455,11 +460,11 @@ freebsd() {
 		fi
 
 		# Set $THEOS and prioritize $THEOS/toolchain
-		# TODO: FreeBSD toolchain path != /linux/ ?
+		# TODO: FreeBSD unique toolchain path != /linux/ ?
 		echo "export THEOS=~/theos" >> "$SHELL_ENV"
 		echo 'export PATH=$THEOS/toolchain/linux/iphone/bin:$PATH' >> "$SHELL_ENV"
 		echo 'export LD_LIBRARY_PATH=$THEOS/toolchain/linux/iphone/lib:$LD_LIBRARY_PATH' >> "$SHELL_ENV"
-		source "$SHELL_ENV"
+		. "$SHELL_ENV"
 		if [[ "$THEOS" ]]; then
 			update "\$THEOS has been successfully set to '$THEOS'!"
 		else
